name: Feature Request
description: File a feature request
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature!
  - type: dropdown
    id: area
    attributes:
      label: Area Select
      description: What part of the PyTorch Live codebase do you have a feature request for?
      options:
        - react-native-pytorch-core (core package)
        - CLI
        - Website/Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the feature you would like to request.
    validations:
      required: true
