/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

const path = require('path');
const pkg = require('./package.json');

module.exports = {
  dependencies: {
    // Automatically generated by expo-dev-client
    ...require('expo-dev-client/dependencies'),

    // These Snack runtime dependencies are required to run the runtime.
    // Because these dependencies are "deps of deps", React Native autolinker won't pick it up.
    // Add all of these if they are not defined in the `package.json`.
    ...dependency('@react-native-async-storage/async-storage'),
    ...dependency('react-native-gesture-handler'),
    ...dependency('react-native-reanimated'),
    ...dependency('react-native-safe-area-context'),
    ...dependency('react-native-view-shot'),
    // There are more dependencies required for Snack runtime, for a full list see:
    //   > node --print "require('snack-runtime/package.json')"
  },
};

function dependency(name) {
  const hasLocalDependency =
    pkg.dependencies[name] || pkg.devDependencies[name];
  // Skip if this dependency is listed in `package.json`, RN linker will pick it up.
  return hasLocalDependency ? undefined : {[name]: {root: resolve(name)}};
}

function resolve(name) {
  return path.dirname(
    require.resolve(path.join(name, 'package.json'), {
      paths: [__dirname],
    }),
  );
}
