/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

// This file was generated by `yarn run codegen-examples`

import React from 'react';
import CodeBlock from '@theme/CodeBlock';

function ImageClassificationDemoExamples() {}


import V0Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v0.tsx';

import V1Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v1.tsx';

import V1DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v1.tsx.diff';

import V2Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v2.tsx';

import V2DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v2.tsx.diff';

import V3Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v3.tsx';

import V3DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v3.tsx.diff';

import V4Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v4.tsx';

import V4DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v4.tsx.diff';

import V5Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v5.tsx';

import V5DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v5.tsx.diff';

import V6Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v6.tsx';

import V6DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v6.tsx.diff';

import V7Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v7.tsx';

import V7DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v7.tsx.diff';

import V8Contents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v8.tsx';

import V8DiffContents from '!!raw-loader!/static/examples/image-classification/ImageClassificationDemo.v8.tsx.diff';

ImageClassificationDemoExamples.V0CodeBlock = function V0CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V0Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V1CodeBlock = function V1CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V1Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V1DiffBlock = function V1DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V1DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V2CodeBlock = function V2CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V2Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V2DiffBlock = function V2DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V2DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V3CodeBlock = function V3CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V3Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V3DiffBlock = function V3DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V3DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V4CodeBlock = function V4CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V4Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V4DiffBlock = function V4DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V4DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V5CodeBlock = function V5CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V5Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V5DiffBlock = function V5DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V5DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V6CodeBlock = function V6CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V6Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V6DiffBlock = function V6DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V6DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V7CodeBlock = function V7CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V7Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V7DiffBlock = function V7DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V7DiffContents}</CodeBlock>
};

ImageClassificationDemoExamples.V8CodeBlock = function V8CodeBlock(props) {
  return <CodeBlock {...props} className="language-tsx">{V8Contents}</CodeBlock>
};

ImageClassificationDemoExamples.V8DiffBlock = function V8DiffBlock(props) {
  return <CodeBlock {...props} className="language-diff">{V8DiffContents}</CodeBlock>
};

export default ImageClassificationDemoExamples;
