/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

// This file was generated by `yarn run codegen-examples`

import React from 'react';
import CodeBlock from '@theme/CodeBlock';

function TextClassificationDemoExamples() { }

import V0Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v0.tsx';

import V1Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v1.tsx';

import V1DiffContents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v1.tsx.diff';

import V2Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v2.tsx';

import V2DiffContents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v2.tsx.diff';

import V3Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v3.tsx';

import V3DiffContents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v3.tsx.diff';

import V4Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v4.tsx';

import V4DiffContents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v4.tsx.diff';

import V5Contents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v5.tsx';

import V5DiffContents from '!!raw-loader!/static/examples/text-classification/TextClassificationDemo.v5.tsx.diff';

TextClassificationDemoExamples.V0CodeBlock = function V0CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V0Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V1CodeBlock = function V1CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V1Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V1DiffBlock = function V1DiffBlock(props) {
  return (
    <CodeBlock {...props} className="language-diff">
      {V1DiffContents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V2CodeBlock = function V2CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V2Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V2DiffBlock = function V2DiffBlock(props) {
  return (
    <CodeBlock {...props} className="language-diff">
      {V2DiffContents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V3CodeBlock = function V3CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V3Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V3DiffBlock = function V3DiffBlock(props) {
  return (
    <CodeBlock {...props} className="language-diff">
      {V3DiffContents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V4CodeBlock = function V4CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V4Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V4DiffBlock = function V4DiffBlock(props) {
  return (
    <CodeBlock {...props} className="language-diff">
      {V4DiffContents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V5CodeBlock = function V5CodeBlock(props) {
  return (
    <CodeBlock {...props} className="language-tsx">
      {V5Contents}
    </CodeBlock>
  );
};

TextClassificationDemoExamples.V5DiffBlock = function V5DiffBlock(props) {
  return (
    <CodeBlock {...props} className="language-diff">
      {V5DiffContents}
    </CodeBlock>
  );
};

export default TextClassificationDemoExamples;
