/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const fbContent = require('internaldocs-fb-helpers').fbContent;

module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [
        'tutorials/get-started',
        'tutorials/get-started-manually',
        'tutorials/add-package',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'tutorials/jsi-tutorials/image-classification-jsi',
        'tutorials/jsi-tutorials/nlp-qa-jsi',
        'tutorials/jsi-tutorials/object-detection-jsi',
        'tutorials/jsi-tutorials/anime-gan-jsi',
        'tutorials/jsi-tutorials/seq2seq-nmt-jsi',
      ],
    },
    {
      type: 'category',
      label: 'On-device Models',
      collapsed: false,
      items: [
        'tutorials/image-classification',
        'tutorials/question-answering',
        'tutorials/mnist-digit-classification',
        'tutorials/prepare-custom-model',
      ],
    },
    {
      type: 'category',
      label: 'Server Models (unstable)',
      collapsed: false,
      items: ['tutorials/server-model', 'tutorials/connecting-to-a-server'],
    },
    fbContent({
      internal: {
        type: 'category',
        label: '[Meta Only]',
        collapsed: false,
        items: ['fb/wikis/creating-a-release', 'fb/wikis/install-ptl-app'],
      },
      external: {},
    }),
    'tutorials/faq',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api/core',
    },
    'api/cli',
    'api/model-spec',
  ],
};
