name: Test PlayTorch SDK with various React Native versions

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-react-native-pytorch-core-android.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/build-react-native-pytorch-core.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'

  workflow_dispatch:

jobs:
  build_with_rn64:
    name: Install Library on RN 0.64 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Init React Native 0.64 project
        run: npx react-native@0.64 init myrn64 --version 0.64
      - name: Install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn64
      - name: Add pickFirst to build.gradle
        env:
          prior: 'android {'
          append: "packagingOptions {pickFirst '**/*.so'}"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn64/android/app
      - name: Enlarge JVM capacity
        env:
          prior: 'FLIPPER_VERSION'
          append: "org.gradle.jvmargs=-Xmx8192m"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" gradle.properties
        working-directory: ./myrn64/android
      - name: Build Android debug
        run: ./gradlew assembleDebug --no-daemon
        working-directory: ./myrn64/android
      - name: Build Android release
        run: ./gradlew assembleRelease --no-daemon
        working-directory: ./myrn64/android

  build_with_rn65:
    name: Install Library on RN 0.65 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Init React Native 0.65 project
        run: npx react-native@0.65 init myrn65 --version 0.65
      - name: Install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn65
      - name: Add pickFirst to build.gradle
        env:
          prior: 'android {'
          append: "packagingOptions {pickFirst '**/*.so'}"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn65/android/app
      - name: Enlarge JVM capacity
        env:
          prior: 'FLIPPER_VERSION'
          append: "org.gradle.jvmargs=-Xmx8192m"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" gradle.properties
        working-directory: ./myrn65/android
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn65/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn65/android

  build_with_rn66:
    name: Install Library on RN 0.66 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Init React Native 0.66 project
        run: npx react-native@0.66 init myrn66 --version 0.66
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn66
      - name: Add pickFirst to build.gradle
        env:
          prior: 'android {'
          append: "packagingOptions {pickFirst '**/*.so'}"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn66/android/app
      - name: Enlarge JVM capacity
        env:
          prior: 'FLIPPER_VERSION'
          append: "org.gradle.jvmargs=-Xmx8192m"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" gradle.properties
        working-directory: ./myrn66/android
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn66/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn66/android

  build_with_rn67:
    name: Install Library on RN 0.67 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Set up Ruby 2.7.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
      - name: Init React Native 0.67 project
        run: npx react-native@0.67 init myrn67 --version 0.67
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn67
      - name: Add pickFirst to build.gradle
        env:
          prior: 'android {'
          append: "packagingOptions {pickFirst '**/*.so'}"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn67/android/app
      - name: Enlarge JVM capacity
        env:
          prior: 'FLIPPER_VERSION'
          append: "org.gradle.jvmargs=-Xmx8192m"
        run: nl=$'\n' && sed -i '' "/${prior}/a\\${nl}${append}${nl}" gradle.properties
        working-directory: ./myrn67/android
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn67/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn67/android

  build_with_rn68:
    name: Install Library on RN 0.68 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Set up Ruby 2.7.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
      - name: Init React Native 0.68 project
        run: npx react-native@0.68 init myrn68 --version 0.68
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn68
      - name: Add pickFirst to build.gradle
        run: nl=$'\n' && sed -i '' "/android {/a\\${nl}packagingOptions {pickFirst '**/*.so'}${nl}" build.gradle
        working-directory: ./myrn68/android/app
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn68/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn68/android

  build_with_rn69:
    name: Install Library on RN 0.69 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
      - name: Init React Native 0.69 project
        run: npx react-native@0.69 init myrn69 --version 0.69
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn69
      - name: Add pickFirst to build.gradle
        run: nl=$'\n' && prior='android {' && append="packagingOptions {pickFirst '**/*.so'}" && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn69/android/app
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn69/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn69/android

  build_with_rn70:
    name: Install Library on RN 0.70 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11 (zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
      - name: Init React Native 0.70 project
        run: npx react-native@0.70 init myrn70 --version 0.70
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn70
      - name: Add pickFirst to build.gradle
        run: nl=$'\n' && prior='android {' && append="packagingOptions {pickFirst '**/*.so'}" && sed -i '' "/${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn70/android/app
      - name: Build Android debug
        run: ./gradlew assembleDebug
        working-directory: ./myrn70/android
      - name: Build Android release
        run: ./gradlew assembleRelease
        working-directory: ./myrn70/android